### ISSUE TITLE
Minor Issue on Example.py

### ISSUE THREAD

**Issue by mpetyx** [Saberr/cronofy-python#1]
Hello,

The example needs a minor fix to work,
the line
`calendars = cronofy.Calendar.all(access_token="")`

should be fix into
`calendars = cronofy.Calendar.all(access_token="", params=None)`

Cheers,
Michael.

**Comment by wagmiwiz** [comment]
Hey @mpetyx, sounds good, pull request? :)

**Comment by mpetyx** [comment]
Something like this could work for you?
https://github.com/Saberr/cronofy-python/pull/2

**Comment by mpetyx** [comment]
closed by https://github.com/Saberr/cronofy-python/pull/2
